language: go
go:
  - 1.x
  - 1.7.1
  - 1.8
  - master
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
env:
  global:
    secure: "M3YOp2LlI7tk6zJt465xvGcXA4Lj2yanPBqlYLskkxZzpdalmBHl/21G8XwkGMZba41JHrkYfwvFYKmYjKwDYBVoRygnLWoMlIwF+qzaQnZmtHcWrelM0lpcxGHpXgIALR5O/qf9NdpjrQiGkzU3aDLC2RfMX7rlKNyH/3Nn/pPPFzRSZTadbCbPltW6zpYMxwmCWGVSTfG1I8hgkIpqUN9Uotd0prFsf/rG53EpKiUH2xN/B2xXMLnW71yLQ9urXo/QAaa4BB8jWEt13gkZdMOhwGxpx3pK0qAqQjN1+RAUC4mFypuaiXBXX0SN4MThQ7vO/it3nQeO5nK7KhPdlaGIHYLMu5rtesiXSjXOtbnv2iS7wmzNpl7iONwzWjou3Xsop9C8lHLmM+vjIzdQeXQGL9DHNIJQP4tw2lURTbZqhskTIHpf1KzcmUwG31cn/Q/dxwJEf4td9N1mufMIDh9ZejkHZ+/l11Xx5+VrlgXEKxHlP6PQMSSrtnp5nWLWMiEeBEbj3MGTUTimbkWfZj/3yHQ2D0IIUJHgnjB4KI56IZxjCs+6Jiynh0jpG7puS1u2+riiAzMLOAfPFucmcFXDdTqgAeSdtlZ0qq8XeYS0+5SLrKN+WRI8cj8kN7Iw2g86xO/YTOaSPna0WT3IcsDzQUWZ/LQleKAZ6OMYAlU="
notifications:
  email: false
  slack:
    secure: nKvobT/phVDM8i/gBsutVecZrB7hSC5duc0j7KALMWEcjGCNlikDAE9O9FjMDmsDoEWr+0u51uIVa9kBJJ3Y1wbrfBNU+WpPlDkLuqUvFAuqIq+eXzVVEgAyH39JZgTs1h6eaLJHmpetHemazLWtbFBV+2/1HxEIsw+kN6kCCsafQn12ZaJouSmKptl27iwVlDiJE9u5xv2FZs80TUxUkf5nIgTKp0otfi1DCKN5mzOHtnFN/wOfqDFUBEsuQqBX6RIMAmFMGQejRP+Op9Op39Bd2Mg8vEPD0wpFqX3PZlqeUbd3MBGsuDs/a8KVXL+WrwXSXk4lPHqrQJhZ7o4xJ0EHkjKpPvvbFmPqceNpsvqofAU2fm1/6yqbmQfD2vxMS4iEFnJzAxFcnniEQLVK1azovLj5ovSxQeWQz80tKBTqVm4FwknBGdn4dkVqCeb5Ofi4+2P4xBSeAQiWFv/ypnT4pkfg26jq3RIyFvIUuIEjl6/57mld5WJKX8/3dxg6sHckNXKvZjgTbldT895k8o3xp62tu3Hnaim6eaMrA0IIgfkPSadBJY6xTs2XGIUJtRWGGWsEB9U0UGe1fWDQfS/OCdsu5UKtfndWgvaRhSEbxAyMsYyi8cCDzR0sgbUjIyCmPEAvoxnvlo3DpBmmqoSl+tWVNu5oB0sBGSIIPjc=
